name: Built Branch and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: "Built Branch and Release"
    runs-on: ubuntu-latest
    steps:
      - uses: alleyinteractive/action-release@develop
        with:
          php-version: '8.2'
          node-version: '22'
